---
title: "Homework 2"
author: "Keyanna Davis"
date: "9/25/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```


#Problem 1

```{r Problem 1}
mr_trash_wheel = readxl::read_excel("./data/trash_wheel.xlsx", 
                                sheet=1)%>%
  janitor::clean_names() %>% 
  select(-x15,-x16,-x17) %>% 
  drop_na() %>% 
mutate(
  sports_balls=round(sports_balls),
  sports_balls=as.integer(sports_balls)
)
    

 
pdata_17 = readxl::read_excel("./data/trash_wheel.xlsx",
                                    sheet=6, skip = 1) %>% 
janitor::clean_names() %>% 
drop_na() %>% 
  mutate(.data=., year="2017"
) 


pdata_18 = readxl::read_excel("./data/trash_wheel.xlsx",
                                    sheet=5, skip=1) %>% 
janitor::clean_names() %>% 
drop_na() %>% 
  mutate(.data=., year="2018"
) 


pdata = merge(pdata_17, pdata_18, by="month") %>% 
  mutate(month = month.name[month] )
    
```






#Problem 2

```{r}

pols_month = read_csv("./data/fivethirtyeight_datasets/pols-month.csv") %>% 
janitor::clean_names() %>% 
  separate(mon, c("year", "month", "day")) %>% 
  mutate(
month = as.numeric(month),
month = month.abb[month] ) %>% 
  mutate( president=prez_dem+prez_gop) %>% 
  select(-prez_dem, -prez_gop,-day)



snp = read_csv("./data/fivethirtyeight_datasets/snp.csv") %>% 
janitor::clean_names() %>% 
  separate(date, c("month", "day", "year")) %>% 
  mutate(
month = as.numeric(month),
month = month.abb[month] )%>% 
  select(year, month, everything())


unemployment = read_csv("./data/fivethirtyeight_datasets/unemployment.csv") %>% 
  janitor::clean_names() %>% 
    pivot_longer(
      jan:dec,
      names_to="month",
      values_to = "day"
    ) %>% 
  mutate(
     day = round(day),
     day = as.integer(day)
  )

pols_snp = full_join(pols_month, snp, by = c("year"="year", "month"="month")) %>% 
  mutate(
    year=as.numeric(year),
    day=as.integer(day))
  

pols_snp_unemploy = full_join(pols_snp, unemployment, by=c( "month"="month", "year"="year", "day"="day")) %>% 
  drop_na()

```





##Problem 3

```{r}
baby_names = read_csv("./data/Popular_Baby_Names.csv") %>% 
  janitor::clean_names() %>% 
  distinct() %>% 
 
  mutate(
  rank = cut(rank, breaks = c(-Inf, 36, 63, Inf),
                       labels = c("highest", "medium", "lowest"))
  )
  
```



